export default function DisclaimerPage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-12">
      <h1 className="text-5xl font-bold mb-8">
        Disclaimer
      </h1>

      <p className="text-gray-600 leading-8">
        The information and tools provided on ToolVerse are intended
        for general informational and educational purposes only.
        While we strive to ensure accuracy, we make no guarantees
        regarding the completeness, reliability or accuracy of any
        information, calculations or results generated by this website.
      </p>

      <section className="mt-10">
        <h2 className="text-2xl font-bold mb-4">
          Calculation Results
        </h2>

        <p className="text-gray-600 leading-8">
          All calculators and tools available on ToolVerse provide
          estimates based on the information entered by users.
          Results should not be considered professional, legal,
          financial, medical or educational advice.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold mb-4">
          No Professional Advice
        </h2>

        <p className="text-gray-600 leading-8">
          The content and tools on this website are not a substitute
          for advice from qualified professionals. Users should seek
          professional guidance before making important decisions
          based on information obtained from ToolVerse.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold mb-4">
          External Links
        </h2>

        <p className="text-gray-600 leading-8">
          ToolVerse may contain links to third-party websites and
          services. We are not responsible for the content, accuracy,
          privacy practices or policies of external websites.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold mb-4">
          Limitation of Liability
        </h2>

        <p className="text-gray-600 leading-8">
          Under no circumstances shall ToolVerse or its owner be held
          liable for any loss, damage or inconvenience arising from
          the use of this website or reliance on its tools and results.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-bold mb-4">
          Contact Information
        </h2>

        <p className="text-gray-600 leading-8">
          If you have questions regarding this Disclaimer, please
          contact:
        </p>

        <p className="mt-3">
          <a
            href="mailto:prajapatikunal412001@gmail.com"
            className="text-[#E5322D]"
          >
            prajapatikunal412001@gmail.com
          </a>
        </p>
      </section>

      <p className="mt-12 text-sm text-gray-500">
        Last Updated: August 2026
      </p>
    </div>
  );
}